// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VirtualPetAdoption.Data;

#nullable disable

namespace VirtualPetAdoption.Migrations
{
    [DbContext(typeof(PetAdoptionContext))]
    partial class PetAdoptionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("VirtualPetAdoption.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EnergyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A calm and relaxed cat who enjoys naps.",
                            EnergyLevel = 2,
                            ImageUrl = "/images/cat.png",
                            Name = "Fluffy",
                            Species = "Cat"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A high-energy dog who loves to play fetch.",
                            EnergyLevel = 5,
                            ImageUrl = "/images/dog.png",
                            Name = "Rex",
                            Species = "Dog"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A friendly rabbit with moderate energy.",
                            EnergyLevel = 3,
                            ImageUrl = "/images/rabbit.png",
                            Name = "Nibbles",
                            Species = "Rabbit"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
